openapi: 3.0.0
info:
  title: API Reference
  description: バックエンドAPI仕様書
  version: 0.1.0
  termsOfService: https://localhost
servers:
  - url: http://localhost
    description: ローカル開発環境
  - url: https://preview
    description: プレビュー環境
  - url: https://production
    description: 本番環境
paths:
  /api/v1/prefectures:
    get:
      tags:
        - default
      summary: prefectures
      parameters:
        - name: X-API-KEY
          in: header
          schema:
            type: string
          example: '{{Access_Key}}'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json;charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '1860'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Sun, 13 Nov 2022 07:45:24 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: c1df6c4f-3863-4499-9545-f1041e9a97a1
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: bh4HMGcTtjMFjWg=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: Root=1-6370a094-342cee2129dc28b2240474c5;Sampled=0
            X-Cache:
              schema:
                type: string
                example: Miss from cloudfront
            Via:
              schema:
                type: number
                example: >-
                  1.1 420b04515afbec0c45b59617f13f792a.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: IAD55-P4
            X-Amz-Cf-Id:
              schema:
                type: string
                example: NMOd4VuK2TCtSZjfrQfXq11rgnCHSxWXiAlR5Ng-qx66E4bjQvUrrw==
          content:
            application/json:
              schema:
                type: object
              example:
                message: null
                result:
                  - prefCode: 1
                    prefName: 北海道
                  - prefCode: 2
                    prefName: 青森県
                  - prefCode: 3
                    prefName: 岩手県
                  - prefCode: 4
                    prefName: 宮城県
                  - prefCode: 5
                    prefName: 秋田県
                  - prefCode: 6
                    prefName: 山形県
                  - prefCode: 7
                    prefName: 福島県
                  - prefCode: 8
                    prefName: 茨城県
                  - prefCode: 9
                    prefName: 栃木県
                  - prefCode: 10
                    prefName: 群馬県
                  - prefCode: 11
                    prefName: 埼玉県
                  - prefCode: 12
                    prefName: 千葉県
                  - prefCode: 13
                    prefName: 東京都
                  - prefCode: 14
                    prefName: 神奈川県
                  - prefCode: 15
                    prefName: 新潟県
                  - prefCode: 16
                    prefName: 富山県
                  - prefCode: 17
                    prefName: 石川県
                  - prefCode: 18
                    prefName: 福井県
                  - prefCode: 19
                    prefName: 山梨県
                  - prefCode: 20
                    prefName: 長野県
                  - prefCode: 21
                    prefName: 岐阜県
                  - prefCode: 22
                    prefName: 静岡県
                  - prefCode: 23
                    prefName: 愛知県
                  - prefCode: 24
                    prefName: 三重県
                  - prefCode: 25
                    prefName: 滋賀県
                  - prefCode: 26
                    prefName: 京都府
                  - prefCode: 27
                    prefName: 大阪府
                  - prefCode: 28
                    prefName: 兵庫県
                  - prefCode: 29
                    prefName: 奈良県
                  - prefCode: 30
                    prefName: 和歌山県
                  - prefCode: 31
                    prefName: 鳥取県
                  - prefCode: 32
                    prefName: 島根県
                  - prefCode: 33
                    prefName: 岡山県
                  - prefCode: 34
                    prefName: 広島県
                  - prefCode: 35
                    prefName: 山口県
                  - prefCode: 36
                    prefName: 徳島県
                  - prefCode: 37
                    prefName: 香川県
                  - prefCode: 38
                    prefName: 愛媛県
                  - prefCode: 39
                    prefName: 高知県
                  - prefCode: 40
                    prefName: 福岡県
                  - prefCode: 41
                    prefName: 佐賀県
                  - prefCode: 42
                    prefName: 長崎県
                  - prefCode: 43
                    prefName: 熊本県
                  - prefCode: 44
                    prefName: 大分県
                  - prefCode: 45
                    prefName: 宮崎県
                  - prefCode: 46
                    prefName: 鹿児島県
                  - prefCode: 47
                    prefName: 沖縄県
  /api/v1/population/composition/perYear:
    get:
      tags:
        - default
      summary: population
      parameters:
        - name: X-API-KEY
          in: header
          schema:
            type: string
          example: '{{Access_Key}}'
        - name: cityCode
          in: query
          schema:
            type: string
          example: '-'
        - name: prefCode
          in: query
          schema:
            type: integer
          example: '11'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json;charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '2966'
            Connection:
              schema:
                type: string
                example: keep-alive
            Date:
              schema:
                type: string
                example: Sun, 13 Nov 2022 07:49:23 GMT
            x-amzn-RequestId:
              schema:
                type: string
                example: d7927aae-0c15-42ed-8f13-3a61f45c156b
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            x-amz-apigw-id:
              schema:
                type: string
                example: bh4sfHeltjMFTsQ=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: Root=1-6370a182-1667bbea098c6883003091bd;Sampled=0
            X-Cache:
              schema:
                type: string
                example: Miss from cloudfront
            Via:
              schema:
                type: number
                example: >-
                  1.1 27dc27c157f4b42ae253527f76742be4.cloudfront.net
                  (CloudFront)
            X-Amz-Cf-Pop:
              schema:
                type: string
                example: IAD55-P4
            X-Amz-Cf-Id:
              schema:
                type: string
                example: sggVRAY6A5GJkLLWsZhjzPJ_4ZYFaPFNTZQRCA35_AniHVSEY513EA==
          content:
            application/json:
              schema:
                type: object
              example:
                message: null
                result:
                  boundaryYear: 2015
                  data:
                    - label: 総人口
                      data:
                        - year: 1960
                          value: 2430871
                        - year: 1965
                          value: 3014983
                        - year: 1970
                          value: 3866472
                        - year: 1975
                          value: 4821340
                        - year: 1980
                          value: 5420480
                        - year: 1985
                          value: 5863678
                        - year: 1990
                          value: 6405319
                        - year: 1995
                          value: 6759311
                        - year: 2000
                          value: 6938006
                        - year: 2005
                          value: 7054243
                        - year: 2010
                          value: 7194556
                        - year: 2015
                          value: 7266534
                        - year: 2020
                          value: 7272830
                        - year: 2025
                          value: 7202953
                        - year: 2030
                          value: 7076167
                        - year: 2035
                          value: 6909319
                        - year: 2040
                          value: 6721414
                        - year: 2045
                          value: 6524800
                    - label: 年少人口
                      data:
                        - year: 1960
                          value: 752024
                          rate: 30.9
                        - year: 1965
                          value: 790961
                          rate: 26.2
                        - year: 1970
                          value: 1002863
                          rate: 25.9
                        - year: 1975
                          value: 1340136
                          rate: 27.7
                        - year: 1980
                          value: 1458421
                          rate: 26.9
                        - year: 1985
                          value: 1380180
                          rate: 23.5
                        - year: 1990
                          value: 1196946
                          rate: 18.6
                        - year: 1995
                          value: 1090395
                          rate: 16.1
                        - year: 2000
                          value: 1024787
                          rate: 14.7
                        - year: 2005
                          value: 986361
                          rate: 13.9
                        - year: 2010
                          value: 953668
                          rate: 13.2
                        - year: 2015
                          value: 910805
                          rate: 12.5
                        - year: 2020
                          value: 871221
                          rate: 11.9
                        - year: 2025
                          value: 819197
                          rate: 11.3
                        - year: 2030
                          value: 778699
                          rate: 11
                        - year: 2035
                          value: 744151
                          rate: 10.7
                        - year: 2040
                          value: 723391
                          rate: 10.7
                        - year: 2045
                          value: 698496
                          rate: 10.7
                    - label: 生産年齢人口
                      data:
                        - year: 1960
                          value: 1545841
                          rate: 63.5
                        - year: 1965
                          value: 2066337
                          rate: 68.5
                        - year: 1970
                          value: 2665020
                          rate: 68.9
                        - year: 1975
                          value: 3223138
                          rate: 66.8
                        - year: 1980
                          value: 3624550
                          rate: 66.8
                        - year: 1985
                          value: 4060573
                          rate: 69.2
                        - year: 1990
                          value: 4660202
                          rate: 72.7
                        - year: 1995
                          value: 4976945
                          rate: 73.6
                        - year: 2000
                          value: 5011202
                          rate: 72.2
                        - year: 2005
                          value: 4892253
                          rate: 69.3
                        - year: 2010
                          value: 4749108
                          rate: 66
                        - year: 2015
                          value: 4507174
                          rate: 62
                        - year: 2020
                          value: 4421637
                          rate: 60.7
                        - year: 2025
                          value: 4350217
                          rate: 60.3
                        - year: 2030
                          value: 4217720
                          rate: 59.6
                        - year: 2035
                          value: 4002341
                          rate: 57.9
                        - year: 2040
                          value: 3700406
                          rate: 55
                        - year: 2045
                          value: 3491511
                          rate: 53.5
                    - label: 老年人口
                      data:
                        - year: 1960
                          value: 133006
                          rate: 5.4
                        - year: 1965
                          value: 157685
                          rate: 5.2
                        - year: 1970
                          value: 198589
                          rate: 5.1
                        - year: 1975
                          value: 256014
                          rate: 5.3
                        - year: 1980
                          value: 333874
                          rate: 6.1
                        - year: 1985
                          value: 420099
                          rate: 7.1
                        - year: 1990
                          value: 530539
                          rate: 8.2
                        - year: 1995
                          value: 681172
                          rate: 10
                        - year: 2000
                          value: 889243
                          rate: 12.8
                        - year: 2005
                          value: 1157006
                          rate: 16.4
                        - year: 2010
                          value: 1464860
                          rate: 20.3
                        - year: 2015
                          value: 1788735
                          rate: 24.6
                        - year: 2020
                          value: 1979972
                          rate: 27.2
                        - year: 2025
                          value: 2033539
                          rate: 28.2
                        - year: 2030
                          value: 2079748
                          rate: 29.3
                        - year: 2035
                          value: 2162827
                          rate: 31.3
                        - year: 2040
                          value: 2297617
                          rate: 34.1
                        - year: 2045
                          value: 2334793
                          rate: 35.7
